CREATE TABLE `platform_billing_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `status` ENUM('TRIAL', 'ACTIVE', 'PAUSED', 'CLOSED') NOT NULL DEFAULT 'TRIAL',
  `plan_name` VARCHAR(160) NOT NULL,
  `billing_cycle` ENUM('MONTHLY', 'QUARTERLY', 'ANNUAL') NOT NULL DEFAULT 'MONTHLY',
  `currency_code` CHAR(3) NOT NULL,
  `recurring_fee` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `included_users` INT UNSIGNED NOT NULL DEFAULT 0,
  `price_per_additional_user` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `included_employees` INT UNSIGNED NOT NULL DEFAULT 0,
  `price_per_additional_employee` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `included_posted_documents` INT UNSIGNED NOT NULL DEFAULT 0,
  `price_per_additional_posted_document` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `tax_rate` DECIMAL(9,4) NOT NULL DEFAULT 0,
  `payment_terms_days` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `next_billing_date` DATE NULL,
  `notes` VARCHAR(1000) NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `platform_billing_accounts_company_key` (`company_id`),
  UNIQUE KEY `platform_billing_accounts_id_company_key` (`id`, `company_id`),
  KEY `platform_billing_accounts_status_next_idx` (`status`, `next_billing_date`),
  CONSTRAINT `platform_billing_accounts_prices_chk` CHECK (
    `recurring_fee` >= 0
    AND `price_per_additional_user` >= 0
    AND `price_per_additional_employee` >= 0
    AND `price_per_additional_posted_document` >= 0
  ),
  CONSTRAINT `platform_billing_accounts_tax_chk` CHECK (`tax_rate` >= 0 AND `tax_rate` <= 100),
  CONSTRAINT `platform_billing_accounts_terms_chk` CHECK (`payment_terms_days` <= 365),
  CONSTRAINT `platform_billing_accounts_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_accounts_created_by_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_accounts_updated_by_fkey` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `platform_billing_invoices` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `billing_account_id` BIGINT UNSIGNED NOT NULL,
  `invoice_number` VARCHAR(60) NOT NULL,
  `state` ENUM('ISSUED', 'VOID') NOT NULL DEFAULT 'ISSUED',
  `period_start` DATE NOT NULL,
  `period_end` DATE NOT NULL,
  `issue_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `currency_code` CHAR(3) NOT NULL,
  `usage_users` INT UNSIGNED NOT NULL,
  `usage_employees` INT UNSIGNED NOT NULL,
  `usage_posted_documents` INT UNSIGNED NOT NULL,
  `usage_operations` INT UNSIGNED NOT NULL,
  `subtotal` DECIMAL(19,4) NOT NULL,
  `tax_rate_snapshot` DECIMAL(9,4) NOT NULL,
  `tax_amount` DECIMAL(19,4) NOT NULL,
  `total_amount` DECIMAL(19,4) NOT NULL,
  `notes` VARCHAR(1000) NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `issued_by_id` BIGINT UNSIGNED NOT NULL,
  `voided_by_id` BIGINT UNSIGNED NULL,
  `voided_at` DATETIME(3) NULL,
  `void_reason` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `platform_billing_invoices_public_id_key` (`public_id`),
  UNIQUE KEY `platform_billing_invoices_number_key` (`invoice_number`),
  UNIQUE KEY `platform_billing_invoices_id_company_key` (`id`, `company_id`),
  UNIQUE KEY `platform_billing_invoices_company_period_key` (`company_id`, `period_start`, `period_end`),
  KEY `platform_billing_invoices_company_issue_idx` (`company_id`, `issue_date`, `id`),
  KEY `platform_billing_invoices_state_due_idx` (`state`, `due_date`),
  CONSTRAINT `platform_billing_invoices_dates_chk` CHECK (`period_end` >= `period_start` AND `due_date` >= `issue_date`),
  CONSTRAINT `platform_billing_invoices_amounts_chk` CHECK (`subtotal` >= 0 AND `tax_amount` >= 0 AND `total_amount` >= 0),
  CONSTRAINT `platform_billing_invoices_tax_chk` CHECK (`tax_rate_snapshot` >= 0 AND `tax_rate_snapshot` <= 100),
  CONSTRAINT `platform_billing_invoices_void_chk` CHECK (
    (`state` = 'ISSUED' AND `voided_by_id` IS NULL AND `voided_at` IS NULL AND `void_reason` IS NULL)
    OR (`state` = 'VOID' AND `voided_by_id` IS NOT NULL AND `voided_at` IS NOT NULL AND `void_reason` IS NOT NULL)
  ),
  CONSTRAINT `platform_billing_invoices_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_invoices_account_fkey` FOREIGN KEY (`billing_account_id`, `company_id`) REFERENCES `platform_billing_accounts` (`id`, `company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_invoices_issued_by_fkey` FOREIGN KEY (`issued_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_invoices_voided_by_fkey` FOREIGN KEY (`voided_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `platform_billing_invoice_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `invoice_id` BIGINT UNSIGNED NOT NULL,
  `line_number` SMALLINT UNSIGNED NOT NULL,
  `line_type` ENUM('RECURRING_FEE', 'ADDITIONAL_USERS', 'ADDITIONAL_EMPLOYEES', 'ADDITIONAL_POSTED_DOCUMENTS', 'ADJUSTMENT') NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `unit_price` DECIMAL(19,4) NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `platform_billing_invoice_lines_invoice_line_key` (`invoice_id`, `line_number`),
  UNIQUE KEY `platform_billing_invoice_lines_id_company_key` (`id`, `company_id`),
  KEY `platform_billing_invoice_lines_company_invoice_idx` (`company_id`, `invoice_id`),
  CONSTRAINT `platform_billing_invoice_lines_quantity_chk` CHECK (`quantity` > 0),
  CONSTRAINT `platform_billing_invoice_lines_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_invoice_lines_invoice_fkey` FOREIGN KEY (`invoice_id`, `company_id`) REFERENCES `platform_billing_invoices` (`id`, `company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `platform_billing_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `invoice_id` BIGINT UNSIGNED NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `method` ENUM('BANK_TRANSFER', 'CARD', 'CASH', 'OTHER') NOT NULL,
  `reference` VARCHAR(160) NULL,
  `notes` VARCHAR(1000) NULL,
  `received_by_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `platform_billing_payments_public_id_key` (`public_id`),
  UNIQUE KEY `platform_billing_payments_id_company_key` (`id`, `company_id`),
  KEY `platform_billing_payments_company_date_idx` (`company_id`, `payment_date`, `id`),
  KEY `platform_billing_payments_invoice_created_idx` (`invoice_id`, `created_at`),
  CONSTRAINT `platform_billing_payments_amount_chk` CHECK (`amount` > 0),
  CONSTRAINT `platform_billing_payments_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_payments_invoice_fkey` FOREIGN KEY (`invoice_id`, `company_id`) REFERENCES `platform_billing_invoices` (`id`, `company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `platform_billing_payments_received_by_fkey` FOREIGN KEY (`received_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
