import {
  localizedReferenceName,
  activeIntlLocale,
  translate as t } from "./i18n";
import { FormEvent,
  useCallback,
  useEffect,
  useMemo,
  useState } from "react";
import { api } from "./api";
import { flattenTree } from "./domain";
import type { Account,
  AccountType,
  CostCenter,
  DefaultChartTemplateApplyResult,
  DefaultChartTemplateStatus,
  ListResponse } from "./types";
import { Button,
  EmptyState,
  Icon,
  Modal,
  Spinner,
  PageHeader,
} from "./ui";

type Notice = (message: string, tone?: "success" | "error") => void;
type Tab = "accounts" | "centers";

async function allPages<T>(path: string) {
  const first = await api<ListResponse<T>>(`${path}${path.includes("?") ? "&" : "?"}page=1&pageSize=100`);
  if (first.meta.totalPages <= 1) return first.data;
  const rest = await Promise.all(Array.from({ length: first.meta.totalPages - 1 }, (_, index) => api<ListResponse<T>>(`${path}${path.includes("?") ? "&" : "?"}page=${index + 2}&pageSize=100`)));
  return [first.data, ...rest.map((result) => result.data)].flat();
}

export function AccountsPage({ notify }: { notify: Notice }) {
  const [tab, setTab] = useState<Tab>("accounts");
  const [accounts, setAccounts] = useState<Account[]>([]); const [centers, setCenters] = useState<CostCenter[]>([]); const [types, setTypes] = useState<AccountType[]>([]);
  const [template, setTemplate] = useState<DefaultChartTemplateStatus | null>(null); const [applyingTemplate, setApplyingTemplate] = useState(false);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [accountForm, setAccountForm] = useState<Account | "new" | null>(null); const [centerForm, setCenterForm] = useState<CostCenter | "new" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = search.trim() ? `?search=${encodeURIComponent(search.trim())}` : ""; const [accountRows, centerRows, typeRows, templateStatus] = await Promise.all([allPages<Account>(`/accounts${query}`), allPages<CostCenter>(`/cost-centers${query}`), api<{ data: AccountType[] }>("/account-types"), api<DefaultChartTemplateStatus>("/accounts/default-template")]); setAccounts(accountRows); setCenters(centerRows); setTypes(typeRows.data); setTemplate(templateStatus); } catch (cause) { setError(cause instanceof Error ? cause.message : t("pages.accounts.001")); } finally { setLoading(false); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  const accountTree = useMemo(() => flattenTree(accounts.filter((item) => !status || String(item.isActive) === status), (item) => item.parentAccountId), [accounts, status]);
  const centerTree = useMemo(() => flattenTree(centers.filter((item) => !status || String(item.isActive) === status), (item) => item.parentId), [centers, status]);
  async function deactivate(kind: Tab, item: Account | CostCenter) { const reason = window.prompt(t("pages.accounts.002", { value1: localizedReferenceName(item) })); if (!reason || reason.trim().length < 3) return; try { await api(`/${kind === "accounts" ? "accounts" : "cost-centers"}/${item.id}/deactivate`, { method: "POST", body: JSON.stringify({ reason: reason.trim() }) }); notify(kind === "accounts" ? t("pages.accounts.003") : t("pages.accounts.004")); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : t("pages.accounts.005"), "error"); } }
  async function applyTemplate() { if (!template || !window.confirm(t("pages.accounts.006", { value1: template.missing.toLocaleString(activeIntlLocale()) }))) return; setApplyingTemplate(true); try { const result = await api<DefaultChartTemplateApplyResult>("/accounts/default-template/apply", { method: "POST" }); notify(t("pages.accounts.007", { value1: result.created.toLocaleString(activeIntlLocale()), value2: result.linked.toLocaleString(activeIntlLocale()) })); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : t("pages.accounts.008"), "error"); } finally { setApplyingTemplate(false); } }
  async function deleteAccount(item: Account) { if (!window.confirm(t("pages.accounts.009", { value1: item.code, value2: localizedReferenceName(item) }))) return; const reason = window.prompt(t("pages.accounts.010")); if (!reason || reason.trim().length < 3) return; try { await api(`/accounts/${item.id}`, { method: "DELETE", body: JSON.stringify({ reason: reason.trim() }) }); notify(t("pages.accounts.011")); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : t("pages.accounts.012"), "error"); } }
  return <section className="workspace-page"><PageHeader kicker={t("pages.accounts.013")} title={t("pages.accounts.014")} description={t("pages.accounts.015")} actions={<Button icon="plus" onClick={() => tab === "accounts" ? setAccountForm("new") : setCenterForm("new")}>{tab === "accounts" ? t("pages.accounts.016") : t("pages.accounts.017")}</Button>} />
    <div className="section-tabs"><button className={tab === "accounts" ? "active" : ""} onClick={() => setTab("accounts")}>{t("pages.accounts.018")}</button><button className={tab === "centers" ? "active" : ""} onClick={() => setTab("centers")}>{t("pages.accounts.019")}</button></div>
    {tab === "accounts" && template && <div className={`chart-template-banner ${template.missing === 0 ? "complete" : ""}`}><div><strong>{localizedReferenceName(template)}</strong><p>{template.missing > 0 ? t("pages.accounts.020", { value1: template.missing.toLocaleString(activeIntlLocale()) }) : t("pages.accounts.021", { value1: template.total.toLocaleString(activeIntlLocale()) })}{template.inactive > 0 ? t("pages.accounts.022", { value1: template.inactive.toLocaleString(activeIntlLocale()) }) : ""}</p></div>{template.missing > 0 && <Button icon="plus" disabled={applyingTemplate || !template.canApply} onClick={() => void applyTemplate()}>{applyingTemplate ? t("pages.accounts.023") : t("pages.accounts.024")}</Button>}</div>}
    <div className="toolbar accounting-filters"><form className="search-box" onSubmit={(e) => { e.preventDefault(); void load(); }}><Icon name="search" size={18} /><input aria-label={t("pages.accounts.025")} value={search} onChange={(e) => setSearch(e.target.value)} placeholder={t("pages.accounts.025")} /><button type="submit">{t("pages.accounts.026")}</button></form><select aria-label={t("pages.accounts.027")} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">{t("pages.accounts.027")}</option><option value="true">{t("pages.accounts.028")}</option><option value="false">{t("pages.accounts.029")}</option></select></div>
    {error ? <div className="error-panel" role="alert"><p>{error}</p><Button variant="secondary" onClick={() => void load()}>{t("pages.accounts.030")}</Button></div> : loading ? <Spinner label={t("pages.accounts.031")} /> : tab === "accounts" ? <AccountTable rows={accountTree} types={types} onEdit={setAccountForm} onDeactivate={(item) => void deactivate("accounts", item)} onDelete={(item) => void deleteAccount(item)} onCreate={() => setAccountForm("new")} /> : <CenterTable rows={centerTree} onEdit={setCenterForm} onDeactivate={(item) => void deactivate("centers", item)} onCreate={() => setCenterForm("new")} />}
    {accountForm && <AccountForm account={accountForm === "new" ? null : accountForm} accounts={accounts} types={types} onClose={() => setAccountForm(null)} onSaved={async () => { setAccountForm(null); notify(accountForm === "new" ? t("pages.accounts.032") : t("pages.accounts.033")); await load(); }} />}
    {centerForm && <CenterForm center={centerForm === "new" ? null : centerForm} centers={centers} onClose={() => setCenterForm(null)} onSaved={async () => { setCenterForm(null); notify(centerForm === "new" ? t("pages.accounts.034") : t("pages.accounts.035")); await load(); }} />}
  </section>;
}

function AccountTable({ rows, types, onEdit, onDeactivate, onDelete, onCreate }: { rows: Array<Account & { treeDepth: number }>; types: AccountType[]; onEdit: (item: Account) => void; onDeactivate: (item: Account) => void; onDelete: (item: Account) => void; onCreate: () => void }) {
  if (!rows.length) return <EmptyState title={t("pages.accounts.036")} description={t("pages.accounts.037")} action={<Button icon="plus" onClick={onCreate}>{t("pages.accounts.038")}</Button>} />;
  return <div className="data-table-wrap" role="region" tabIndex={0} aria-label={t("common.scrollableTable")}><table className="data-table accounting-tree"><thead><tr><th>{t("pages.accounts.039")}</th><th>{t("pages.accounts.040")}</th><th>{t("pages.accounts.041")}</th><th>{t("pages.accounts.042")}</th><th>{t("pages.accounts.043")}</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><div className="tree-label" style={{ paddingInlineStart: `${item.treeDepth * 24}px` }}><span className="tree-branch">{item.treeDepth ? "↳" : "●"}</span><div><strong dir="ltr">{item.code}</strong><span>{localizedReferenceName(item)}{item.sourceTemplateCode && <small className="template-origin">{t("pages.accounts.044")}</small>}</span></div></div></td><td>{localizedReferenceName(types.find((type) => type.id === item.accountTypeId)) || "—"}</td><td>{item.level.toLocaleString(activeIntlLocale())}</td><td>{item.allowsPosting ? <span className="status-chip active">{t("pages.accounts.045")}</span> : item.isControlAccount ? t("pages.accounts.046") : t("pages.accounts.047")}</td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? t("pages.accounts.028") : t("pages.accounts.029")}</span></td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>{t("pages.accounts.048")}</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>{t("pages.accounts.049")}</Button>}<Button variant="ghost" icon="trash" onClick={() => onDelete(item)}>{t("pages.accounts.050")}</Button></div></td></tr>)}</tbody></table></div>;
}

function CenterTable({ rows, onEdit, onDeactivate, onCreate }: { rows: Array<CostCenter & { treeDepth: number }>; onEdit: (item: CostCenter) => void; onDeactivate: (item: CostCenter) => void; onCreate: () => void }) {
  if (!rows.length) return <EmptyState title={t("pages.accounts.051")} description={t("pages.accounts.052")} action={<Button icon="plus" onClick={onCreate}>{t("pages.accounts.053")}</Button>} />;
  return <div className="data-table-wrap" role="region" tabIndex={0} aria-label={t("common.scrollableTable")}><table className="data-table accounting-tree"><thead><tr><th>{t("pages.accounts.054")}</th><th>{t("pages.accounts.055")}</th><th>{t("pages.accounts.043")}</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><div className="tree-label" style={{ paddingInlineStart: `${item.treeDepth * 24}px` }}><span className="tree-branch">{item.treeDepth ? "↳" : "●"}</span><div><strong dir="ltr">{item.code}</strong><span>{localizedReferenceName(item)}</span></div></div></td><td>{item.nameEn || "—"}</td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? t("pages.accounts.028") : t("pages.accounts.029")}</span></td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>{t("pages.accounts.048")}</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>{t("pages.accounts.049")}</Button>}</div></td></tr>)}</tbody></table></div>;
}

function AccountForm({ account, accounts, types, onClose, onSaved }: { account: Account | null; accounts: Account[]; types: AccountType[]; onClose: () => void; onSaved: () => void }) {
  const [accountTypeId, setAccountTypeId] = useState(account?.accountTypeId ?? types[0]?.id ?? ""); const [parentAccountId, setParentAccountId] = useState(account?.parentAccountId ?? ""); const [code, setCode] = useState(account?.code ?? ""); const [nameAr, setNameAr] = useState(account?.nameAr ?? ""); const [nameEn, setNameEn] = useState(account?.nameEn ?? ""); const [allowsPosting, setAllowsPosting] = useState(account?.allowsPosting ?? false); const [isControlAccount, setControl] = useState(account?.isControlAccount ?? false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const parents = accounts.filter((item) => item.id !== account?.id && item.isActive && !item.allowsPosting);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await api(account ? `/accounts/${account.id}` : "/accounts", { method: account ? "PATCH" : "POST", body: JSON.stringify({ accountTypeId, parentAccountId: parentAccountId || null, code: code.trim(), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null, allowsPosting, isControlAccount }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("pages.accounts.056")); } finally { setSaving(false); } }
  return <Modal title={account ? t("pages.accounts.057") : t("pages.accounts.016")} description={t("pages.accounts.058")} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}<div className="form-grid"><label><span>{t("pages.accounts.059")}</span><input value={code} onChange={(e) => setCode(e.target.value)} required /></label><label><span>{t("pages.accounts.060")}</span><select value={accountTypeId} onChange={(e) => setAccountTypeId(e.target.value)} required>{types.map((type) => <option key={type.id} value={type.id}>{localizedReferenceName(type)}</option>)}</select></label><label><span>{t("pages.accounts.061")}</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label><span>{t("pages.accounts.055")}</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label><label className="full"><span>{t("pages.accounts.062")}</span><select value={parentAccountId} onChange={(e) => setParentAccountId(e.target.value)}><option value="">{t("pages.accounts.063")}</option>{parents.map((item) => <option key={item.id} value={item.id}>{item.code} — {localizedReferenceName(item)}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={allowsPosting} onChange={(e) => setAllowsPosting(e.target.checked)} /><span>{t("pages.accounts.064")}</span></label><label className="check-field"><input type="checkbox" checked={isControlAccount} onChange={(e) => setControl(e.target.checked)} /><span>{t("pages.accounts.046")}</span></label></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>{t("pages.accounts.065")}</Button><Button type="submit" disabled={saving}>{saving ? t("pages.accounts.066") : t("pages.accounts.067")}</Button></div></form></Modal>;
}

function CenterForm({ center, centers, onClose, onSaved }: { center: CostCenter | null; centers: CostCenter[]; onClose: () => void; onSaved: () => void }) {
  const [parentId, setParentId] = useState(center?.parentId ?? ""); const [code, setCode] = useState(center?.code ?? ""); const [nameAr, setNameAr] = useState(center?.nameAr ?? ""); const [nameEn, setNameEn] = useState(center?.nameEn ?? ""); const [error, setError] = useState("");
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); try { await api(center ? `/cost-centers/${center.id}` : "/cost-centers", { method: center ? "PATCH" : "POST", body: JSON.stringify({ parentId: parentId || null, ...(!center ? { code: code.trim() } : {}), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("pages.accounts.068")); } }
  return <Modal title={center ? t("pages.accounts.069") : t("pages.accounts.017")} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}<div className="form-grid"><label><span>{t("pages.accounts.059")}</span><input value={code} onChange={(e) => setCode(e.target.value)} disabled={Boolean(center)} required /></label><label><span>{t("pages.accounts.070")}</span><select value={parentId} onChange={(e) => setParentId(e.target.value)}><option value="">{t("pages.accounts.071")}</option>{centers.filter((item) => item.id !== center?.id && item.isActive).map((item) => <option key={item.id} value={item.id}>{item.code} — {localizedReferenceName(item)}</option>)}</select></label><label><span>{t("pages.accounts.061")}</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label><span>{t("pages.accounts.055")}</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>{t("pages.accounts.065")}</Button><Button type="submit">{t("pages.accounts.067")}</Button></div></form></Modal>;
}
