import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { flattenTree } from "./domain";
import type { Account, AccountType, CostCenter, DefaultChartTemplateApplyResult, DefaultChartTemplateStatus, ListResponse } from "./types";
import { Button, EmptyState, Icon, Modal, Spinner } from "./ui";

type Notice = (message: string, tone?: "success" | "error") => void;
type Tab = "accounts" | "centers";

async function allPages<T>(path: string) {
  const first = await api<ListResponse<T>>(`${path}${path.includes("?") ? "&" : "?"}page=1&pageSize=100`);
  if (first.meta.totalPages <= 1) return first.data;
  const rest = await Promise.all(Array.from({ length: first.meta.totalPages - 1 }, (_, index) => api<ListResponse<T>>(`${path}${path.includes("?") ? "&" : "?"}page=${index + 2}&pageSize=100`)));
  return [first.data, ...rest.map((result) => result.data)].flat();
}

export function AccountsPage({ notify }: { notify: Notice }) {
  const [tab, setTab] = useState<Tab>("accounts");
  const [accounts, setAccounts] = useState<Account[]>([]); const [centers, setCenters] = useState<CostCenter[]>([]); const [types, setTypes] = useState<AccountType[]>([]);
  const [template, setTemplate] = useState<DefaultChartTemplateStatus | null>(null); const [applyingTemplate, setApplyingTemplate] = useState(false);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [accountForm, setAccountForm] = useState<Account | "new" | null>(null); const [centerForm, setCenterForm] = useState<CostCenter | "new" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = search.trim() ? `?search=${encodeURIComponent(search.trim())}` : ""; const [accountRows, centerRows, typeRows, templateStatus] = await Promise.all([allPages<Account>(`/accounts${query}`), allPages<CostCenter>(`/cost-centers${query}`), api<{ data: AccountType[] }>("/account-types"), api<DefaultChartTemplateStatus>("/accounts/default-template")]); setAccounts(accountRows); setCenters(centerRows); setTypes(typeRows.data); setTemplate(templateStatus); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل الدليل المحاسبي."); } finally { setLoading(false); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  const accountTree = useMemo(() => flattenTree(accounts.filter((item) => !status || String(item.isActive) === status), (item) => item.parentAccountId), [accounts, status]);
  const centerTree = useMemo(() => flattenTree(centers.filter((item) => !status || String(item.isActive) === status), (item) => item.parentId), [centers, status]);
  async function deactivate(kind: Tab, item: Account | CostCenter) { const reason = window.prompt(`سبب تعطيل «${item.nameAr}» (3 أحرف على الأقل):`); if (!reason || reason.trim().length < 3) return; try { await api(`/${kind === "accounts" ? "accounts" : "cost-centers"}/${item.id}/deactivate`, { method: "POST", body: JSON.stringify({ reason: reason.trim() }) }); notify(kind === "accounts" ? "تم تعطيل الحساب." : "تم تعطيل مركز التكلفة."); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر التعطيل.", "error"); } }
  async function applyTemplate() { if (!template || !window.confirm(`سيضيف النظام ${template.missing.toLocaleString("ar-SA")} حسابًا مفقودًا فقط، ولن يغيّر حساباتك الحالية. هل تريد المتابعة؟`)) return; setApplyingTemplate(true); try { const result = await api<DefaultChartTemplateApplyResult>("/accounts/default-template/apply", { method: "POST" }); notify(`اكتمل الدليل: أضيف ${result.created.toLocaleString("ar-SA")} وربط ${result.linked.toLocaleString("ar-SA")} حسابًا موجودًا.`); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر تطبيق الدليل الافتراضي.", "error"); } finally { setApplyingTemplate(false); } }
  async function deleteAccount(item: Account) { if (!window.confirm(`حذف الحساب «${item.code} — ${item.nameAr}» نهائيًا؟ لا يُسمح بالحذف إذا كان مستخدمًا أو تحته فروع.`)) return; const reason = window.prompt("سبب الحذف (3 أحرف على الأقل):"); if (!reason || reason.trim().length < 3) return; try { await api(`/accounts/${item.id}`, { method: "DELETE", body: JSON.stringify({ reason: reason.trim() }) }); notify("تم حذف الحساب غير المستخدم."); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر حذف الحساب.", "error"); } }
  return <section className="workspace-page"><header className="page-heading"><div><span className="section-kicker">الإعداد المحاسبي</span><h1>دليل الحسابات ومراكز التكلفة</h1><p>إدارة الهيكل الشجري للحسابات القابلة للترحيل ومراكز التحليل المالي.</p></div><Button icon="plus" onClick={() => tab === "accounts" ? setAccountForm("new") : setCenterForm("new")}>{tab === "accounts" ? "حساب جديد" : "مركز تكلفة جديد"}</Button></header>
    <div className="section-tabs"><button className={tab === "accounts" ? "active" : ""} onClick={() => setTab("accounts")}>دليل الحسابات</button><button className={tab === "centers" ? "active" : ""} onClick={() => setTab("centers")}>مراكز التكلفة</button></div>
    {tab === "accounts" && template && <div className={`chart-template-banner ${template.missing === 0 ? "complete" : ""}`}><div><strong>{template.nameAr}</strong><p>{template.missing > 0 ? `يوجد ${template.missing.toLocaleString("ar-SA")} حسابًا مقترحًا غير موجود. الإضافة لا تستبدل أي تخصيص حالي.` : `الدليل مكتمل (${template.total.toLocaleString("ar-SA")} حسابًا) ويمكنك تعديل أرقامه وأسمائه أو حذف الحسابات غير المستخدمة.`}{template.inactive > 0 ? ` يوجد ${template.inactive.toLocaleString("ar-SA")} حسابًا معطّلًا وسيبقى معطّلًا.` : ""}</p></div>{template.missing > 0 && <Button icon="plus" disabled={applyingTemplate || !template.canApply} onClick={() => void applyTemplate()}>{applyingTemplate ? "جارٍ الإضافة…" : "إكمال الدليل الافتراضي"}</Button>}</div>}
    <div className="toolbar accounting-filters"><form className="search-box" onSubmit={(e) => { e.preventDefault(); void load(); }}><Icon name="search" size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="الرمز أو الاسم" /><button>بحث</button></form><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">كل الحالات</option><option value="true">نشط</option><option value="false">معطل</option></select></div>
    {error ? <div className="error-panel"><p>{error}</p><Button variant="secondary" onClick={() => void load()}>إعادة المحاولة</Button></div> : loading ? <Spinner label="جارٍ تحميل الدليل المحاسبي" /> : tab === "accounts" ? <AccountTable rows={accountTree} types={types} onEdit={setAccountForm} onDeactivate={(item) => void deactivate("accounts", item)} onDelete={(item) => void deleteAccount(item)} onCreate={() => setAccountForm("new")} /> : <CenterTable rows={centerTree} onEdit={setCenterForm} onDeactivate={(item) => void deactivate("centers", item)} onCreate={() => setCenterForm("new")} />}
    {accountForm && <AccountForm account={accountForm === "new" ? null : accountForm} accounts={accounts} types={types} onClose={() => setAccountForm(null)} onSaved={async () => { setAccountForm(null); notify(accountForm === "new" ? "تم إنشاء الحساب." : "تم تحديث الحساب."); await load(); }} />}
    {centerForm && <CenterForm center={centerForm === "new" ? null : centerForm} centers={centers} onClose={() => setCenterForm(null)} onSaved={async () => { setCenterForm(null); notify(centerForm === "new" ? "تم إنشاء مركز التكلفة." : "تم تحديث مركز التكلفة."); await load(); }} />}
  </section>;
}

function AccountTable({ rows, types, onEdit, onDeactivate, onDelete, onCreate }: { rows: Array<Account & { treeDepth: number }>; types: AccountType[]; onEdit: (item: Account) => void; onDeactivate: (item: Account) => void; onDelete: (item: Account) => void; onCreate: () => void }) {
  if (!rows.length) return <EmptyState title="لا توجد حسابات" description="أنشئ الحسابات الرئيسية أولًا، ثم أضف الحسابات الفرعية القابلة للترحيل." action={<Button icon="plus" onClick={onCreate}>إنشاء حساب</Button>} />;
  return <div className="data-table-wrap"><table className="data-table accounting-tree"><thead><tr><th>الحساب</th><th>النوع</th><th>المستوى</th><th>طبيعة الحساب</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><div className="tree-label" style={{ paddingInlineStart: `${item.treeDepth * 24}px` }}><span className="tree-branch">{item.treeDepth ? "↳" : "●"}</span><div><strong dir="ltr">{item.code}</strong><span>{item.nameAr}{item.sourceTemplateCode && <small className="template-origin">بدأ من القالب</small>}</span></div></div></td><td>{types.find((type) => type.id === item.accountTypeId)?.nameAr ?? "—"}</td><td>{item.level.toLocaleString("ar-SA")}</td><td>{item.allowsPosting ? <span className="status-chip active">قابل للترحيل</span> : item.isControlAccount ? "حساب رقابي" : "تجميعي"}</td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? "نشط" : "معطل"}</span></td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>تعديل</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>تعطيل</Button>}<Button variant="ghost" icon="trash" onClick={() => onDelete(item)}>حذف</Button></div></td></tr>)}</tbody></table></div>;
}

function CenterTable({ rows, onEdit, onDeactivate, onCreate }: { rows: Array<CostCenter & { treeDepth: number }>; onEdit: (item: CostCenter) => void; onDeactivate: (item: CostCenter) => void; onCreate: () => void }) {
  if (!rows.length) return <EmptyState title="لا توجد مراكز تكلفة" description="أضف مركزًا رئيسيًا أو فرعيًا لبدء التحليل حسب الإدارات والمشروعات." action={<Button icon="plus" onClick={onCreate}>إنشاء مركز</Button>} />;
  return <div className="data-table-wrap"><table className="data-table accounting-tree"><thead><tr><th>المركز</th><th>الاسم الإنجليزي</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><div className="tree-label" style={{ paddingInlineStart: `${item.treeDepth * 24}px` }}><span className="tree-branch">{item.treeDepth ? "↳" : "●"}</span><div><strong dir="ltr">{item.code}</strong><span>{item.nameAr}</span></div></div></td><td>{item.nameEn || "—"}</td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? "نشط" : "معطل"}</span></td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>تعديل</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>تعطيل</Button>}</div></td></tr>)}</tbody></table></div>;
}

function AccountForm({ account, accounts, types, onClose, onSaved }: { account: Account | null; accounts: Account[]; types: AccountType[]; onClose: () => void; onSaved: () => void }) {
  const [accountTypeId, setAccountTypeId] = useState(account?.accountTypeId ?? types[0]?.id ?? ""); const [parentAccountId, setParentAccountId] = useState(account?.parentAccountId ?? ""); const [code, setCode] = useState(account?.code ?? ""); const [nameAr, setNameAr] = useState(account?.nameAr ?? ""); const [nameEn, setNameEn] = useState(account?.nameEn ?? ""); const [allowsPosting, setAllowsPosting] = useState(account?.allowsPosting ?? false); const [isControlAccount, setControl] = useState(account?.isControlAccount ?? false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const parents = accounts.filter((item) => item.id !== account?.id && item.isActive && !item.allowsPosting);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await api(account ? `/accounts/${account.id}` : "/accounts", { method: account ? "PATCH" : "POST", body: JSON.stringify({ accountTypeId, parentAccountId: parentAccountId || null, code: code.trim(), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null, allowsPosting, isControlAccount }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ الحساب."); } finally { setSaving(false); } }
  return <Modal title={account ? "تعديل الحساب" : "حساب جديد"} description="الحسابات التجميعية فقط يمكن اختيارها كحساب أب، والحساب ذو الفروع لا يقبل الترحيل المباشر." onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label><span>الرمز</span><input value={code} onChange={(e) => setCode(e.target.value)} required /></label><label><span>نوع الحساب</span><select value={accountTypeId} onChange={(e) => setAccountTypeId(e.target.value)} required>{types.map((type) => <option key={type.id} value={type.id}>{type.nameAr}</option>)}</select></label><label><span>الاسم العربي</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label><span>الاسم الإنجليزي</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label><label className="full"><span>الحساب الأب</span><select value={parentAccountId} onChange={(e) => setParentAccountId(e.target.value)}><option value="">حساب رئيسي</option>{parents.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.nameAr}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={allowsPosting} onChange={(e) => setAllowsPosting(e.target.checked)} /><span>قابل للترحيل المباشر</span></label><label className="check-field"><input type="checkbox" checked={isControlAccount} onChange={(e) => setControl(e.target.checked)} /><span>حساب رقابي</span></label></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button type="submit" disabled={saving}>{saving ? "جارٍ الحفظ…" : "حفظ"}</Button></div></form></Modal>;
}

function CenterForm({ center, centers, onClose, onSaved }: { center: CostCenter | null; centers: CostCenter[]; onClose: () => void; onSaved: () => void }) {
  const [parentId, setParentId] = useState(center?.parentId ?? ""); const [code, setCode] = useState(center?.code ?? ""); const [nameAr, setNameAr] = useState(center?.nameAr ?? ""); const [nameEn, setNameEn] = useState(center?.nameEn ?? ""); const [error, setError] = useState("");
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); try { await api(center ? `/cost-centers/${center.id}` : "/cost-centers", { method: center ? "PATCH" : "POST", body: JSON.stringify({ parentId: parentId || null, ...(!center ? { code: code.trim() } : {}), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ المركز."); } }
  return <Modal title={center ? "تعديل مركز التكلفة" : "مركز تكلفة جديد"} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label><span>الرمز</span><input value={code} onChange={(e) => setCode(e.target.value)} disabled={Boolean(center)} required /></label><label><span>المركز الأب</span><select value={parentId} onChange={(e) => setParentId(e.target.value)}><option value="">مركز رئيسي</option>{centers.filter((item) => item.id !== center?.id && item.isActive).map((item) => <option key={item.id} value={item.id}>{item.code} — {item.nameAr}</option>)}</select></label><label><span>الاسم العربي</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label><span>الاسم الإنجليزي</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button type="submit">حفظ</Button></div></form></Modal>;
}
