import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./api";
import type { AdminUser, ListResponse, Permission, Role, UserRole, UserSession } from "./types";
import { Button, EmptyState, Modal, Pagination, Spinner } from "./ui";

type Notice = (message: string, tone?: "success" | "error") => void;
type Tab = "users" | "roles" | "sessions";

export function AdminPage({ notify }: { notify: Notice }) {
  const [tab, setTab] = useState<Tab>("users");
  return <section className="workspace-page"><header className="page-heading"><div><span className="section-kicker">التحكم بالوصول</span><h1>المستخدمون والأدوار والصلاحيات</h1><p>إدارة وصول فريق العمل بأدوار معزولة لكل شركة، مع إبطال الجلسات فور تغير الصلاحيات.</p></div></header><div className="section-tabs"><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}>المستخدمون</button><button className={tab === "roles" ? "active" : ""} onClick={() => setTab("roles")}>الأدوار والصلاحيات</button><button className={tab === "sessions" ? "active" : ""} onClick={() => setTab("sessions")}>جلساتي</button></div>{tab === "users" ? <UsersTab notify={notify} /> : tab === "roles" ? <RolesTab notify={notify} /> : <SessionsTab notify={notify} />}</section>;
}

function UsersTab({ notify }: { notify: Notice }) {
  const [rows, setRows] = useState<AdminUser[]>([]), [roles, setRoles] = useState<Role[]>([]), [page, setPage] = useState(1), [totalPages, setTotalPages] = useState(1), [total, setTotal] = useState(0);
  const [search, setSearch] = useState(""), [status, setStatus] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [editing, setEditing] = useState<AdminUser | "new" | null>(null), [roleUser, setRoleUser] = useState<AdminUser | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ page: String(page), pageSize: "20" }); if (search.trim()) query.set("search", search.trim()); if (status) query.set("status", status); const [users, roleResult] = await Promise.all([api<ListResponse<AdminUser>>(`/users?${query}`), api<{ data: Role[] }>("/roles")]); setRows(users.data); setTotal(users.meta.total); setTotalPages(users.meta.totalPages); setRoles(roleResult.data.filter((item) => item.isActive)); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل المستخدمين."); } finally { setLoading(false); } }, [page, search, status]);
  useEffect(() => { void load(); }, [load]);
  async function disable(user: AdminUser) { const reason = window.prompt(`سبب تعطيل «${user.nameAr}» (3 أحرف على الأقل):`); if (!reason || reason.trim().length < 3) return; try { await api(`/users/${user.id}/disable`, { method: "POST", body: JSON.stringify({ reason: reason.trim() }) }); notify("تم تعطيل المستخدم وإلغاء جلساته."); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر التعطيل.", "error"); } }
  return <>{<div className="toolbar"><form className="search-box" onSubmit={(e) => { e.preventDefault(); setPage(1); void load(); }}><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="الاسم أو البريد الإلكتروني"/><button>بحث</button></form><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">كل الحالات</option><option value="ACTIVE">نشط</option><option value="LOCKED">مقفل</option><option value="DISABLED">معطل</option></select><Button icon="plus" onClick={() => setEditing("new")}>مستخدم جديد</Button></div>}{error ? <div className="error-panel">{error}</div> : loading ? <Spinner label="جارٍ تحميل المستخدمين"/> : !rows.length ? <EmptyState title="لا توجد نتائج" description="غيّر البحث أو أنشئ مستخدمًا جديدًا."/> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>المستخدم</th><th>الحالة</th><th>آخر دخول</th><th></th></tr></thead><tbody>{rows.map((user) => <tr key={user.id}><td><strong>{user.nameAr}</strong><small dir="ltr">{user.email}</small></td><td><span className={`status-chip ${user.status === "ACTIVE" ? "active" : "inactive"}`}>{user.status === "ACTIVE" ? "نشط" : user.status === "LOCKED" ? "مقفل" : "معطل"}</span></td><td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString("ar-SA") : "لم يدخل بعد"}</td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => setEditing(user)}>تعديل</Button><Button variant="ghost" onClick={() => setRoleUser(user)}>الأدوار</Button>{user.status !== "DISABLED" && <Button variant="ghost" icon="ban" onClick={() => void disable(user)}>تعطيل</Button>}</div></td></tr>)}</tbody></table></div>}<Pagination page={page} totalPages={totalPages} total={total} onChange={setPage}/>{editing && <UserForm user={editing === "new" ? null : editing} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); notify("تم حفظ المستخدم."); await load(); }}/>} {roleUser && <UserRoles user={roleUser} roles={roles} onClose={() => setRoleUser(null)} onSaved={async () => { setRoleUser(null); notify("تم تحديث أدوار المستخدم وإلغاء جلساته السابقة."); await load(); }}/>}</>;
}

function UserForm({ user, onClose, onSaved }: { user: AdminUser | null; onClose: () => void; onSaved: () => void }) {
  const [nameAr, setNameAr] = useState(user?.nameAr ?? ""), [nameEn, setNameEn] = useState(user?.nameEn ?? ""), [email, setEmail] = useState(user?.email ?? ""), [password, setPassword] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await api(user ? `/users/${user.id}` : "/users", { method: user ? "PATCH" : "POST", body: JSON.stringify(user ? { nameAr: nameAr.trim(), nameEn: nameEn.trim() || null } : { email: email.trim(), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null, temporaryPassword: password }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ المستخدم."); } finally { setSaving(false); } }
  return <Modal title={user ? "تعديل المستخدم" : "مستخدم جديد"} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label><span>الاسم العربي</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required/></label><label><span>الاسم الإنجليزي</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)}/></label>{!user && <><label><span>البريد الإلكتروني</span><input dir="ltr" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/></label><label><span>كلمة المرور المؤقتة</span><input dir="ltr" type="password" minLength={12} value={password} onChange={(e) => setPassword(e.target.value)} required/><small>12 حرفًا على الأقل.</small></label></>}</div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button type="submit" disabled={saving}>{saving ? "جارٍ الحفظ…" : "حفظ"}</Button></div></form></Modal>;
}

function UserRoles({ user, roles, onClose, onSaved }: { user: AdminUser; roles: Role[]; onClose: () => void; onSaved: () => void }) {
  const [selected, setSelected] = useState<string[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { void api<{ data: UserRole[] }>(`/users/${user.id}/roles`).then((result) => setSelected(result.data.map((item) => item.roleId))).catch((cause) => setError(cause instanceof Error ? cause.message : "تعذر تحميل الأدوار.")).finally(() => setLoading(false)); }, [user.id]);
  async function save() { try { await api(`/users/${user.id}/roles`, { method: "PUT", body: JSON.stringify({ roleIds: selected }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ الأدوار."); } }
  return <Modal title={`أدوار ${user.nameAr}`} description="يتطلب التغيير من المستخدم تسجيل الدخول من جديد." onClose={onClose}>{loading ? <Spinner/> : <div className="selection-list">{error && <div className="form-error">{error}</div>}{roles.map((role) => <label className="check-field" key={role.id}><input type="checkbox" checked={selected.includes(role.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, role.id] : selected.filter((id) => id !== role.id))}/><span><strong>{role.nameAr}</strong><small>{role.permissions.length.toLocaleString("ar-SA")} صلاحية</small></span></label>)}</div>}<div className="form-actions"><Button variant="ghost" onClick={onClose}>إلغاء</Button><Button onClick={() => void save()} disabled={loading}>حفظ الإسناد</Button></div></Modal>;
}

function RolesTab({ notify }: { notify: Notice }) {
  const [roles, setRoles] = useState<Role[]>([]), [permissions, setPermissions] = useState<Permission[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [editing, setEditing] = useState<Role | "new" | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [r, p] = await Promise.all([api<{ data: Role[] }>("/roles"), api<{ data: Permission[] }>("/permissions")]); setRoles(r.data); setPermissions(p.data); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل الأدوار."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function deactivate(role: Role) { const reason = window.prompt(`سبب تعطيل «${role.nameAr}»:`); if (!reason || reason.trim().length < 3) return; try { await api(`/roles/${role.id}/deactivate`, { method: "POST", body: JSON.stringify({ reason: reason.trim() }) }); notify("تم تعطيل الدور وإزالة إسناداته."); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر تعطيل الدور.", "error"); } }
  return <>{<div className="toolbar"><p>الأدوار النظامية محمية من التعديل لتجنب فقد الوصول الإداري.</p><Button icon="plus" onClick={() => setEditing("new")}>دور جديد</Button></div>}{error ? <div className="error-panel">{error}</div> : loading ? <Spinner/> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>الدور</th><th>المستخدمون</th><th>الصلاحيات</th><th>الحالة</th><th></th></tr></thead><tbody>{roles.map((role) => <tr key={role.id}><td><strong>{role.nameAr}</strong><small dir="ltr">{role.code}{role.isSystemRole ? " · SYSTEM" : ""}</small></td><td>{role.assignedUsers.toLocaleString("ar-SA")}</td><td>{role.permissions.length.toLocaleString("ar-SA")}</td><td><span className={`status-chip ${role.isActive ? "active" : "inactive"}`}>{role.isActive ? "نشط" : "معطل"}</span></td><td>{!role.isSystemRole && role.isActive && <div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => setEditing(role)}>تعديل</Button><Button variant="ghost" icon="ban" onClick={() => void deactivate(role)}>تعطيل</Button></div>}</td></tr>)}</tbody></table></div>}{editing && <RoleForm role={editing === "new" ? null : editing} permissions={permissions} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); notify("تم حفظ الدور والصلاحيات."); await load(); }}/>}</>;
}

function RoleForm({ role, permissions, onClose, onSaved }: { role: Role | null; permissions: Permission[]; onClose: () => void; onSaved: () => void }) {
  const [code, setCode] = useState(role?.code ?? ""), [nameAr, setNameAr] = useState(role?.nameAr ?? ""), [nameEn, setNameEn] = useState(role?.nameEn ?? ""), [selected, setSelected] = useState(role?.permissionIds ?? []), [error, setError] = useState("");
  const groups = useMemo(() => Object.entries(permissions.reduce<Record<string, Permission[]>>((result, item) => { (result[item.module] ??= []).push(item); return result; }, {})), [permissions]);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); try { if (role) { await api(`/roles/${role.id}`, { method: "PATCH", body: JSON.stringify({ nameAr: nameAr.trim(), nameEn: nameEn.trim() || null }) }); await api(`/roles/${role.id}/permissions`, { method: "PUT", body: JSON.stringify({ permissionIds: selected }) }); } else await api("/roles", { method: "POST", body: JSON.stringify({ code: code.trim(), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null, permissionIds: selected }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ الدور."); } }
  return <Modal wide title={role ? "تعديل الدور" : "دور جديد"} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label><span>الرمز</span><input dir="ltr" value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} pattern="[A-Za-z][A-Za-z0-9_]{1,79}" disabled={Boolean(role)} required/></label><label><span>الاسم العربي</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required/></label><label><span>الاسم الإنجليزي</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)}/></label><div className="full permission-groups">{groups.map(([module, items]) => <fieldset key={module}><legend>{module}</legend>{items?.map((permission) => <label className="check-field" key={permission.id}><input type="checkbox" checked={selected.includes(permission.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, permission.id] : selected.filter((id) => id !== permission.id))}/><span>{permission.descriptionAr}<small dir="ltr">{permission.code}</small></span></label>)}</fieldset>)}</div></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button type="submit">حفظ</Button></div></form></Modal>;
}

function SessionsTab({ notify }: { notify: Notice }) {
  const [sessions, setSessions] = useState<UserSession[]>([]), [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setSessions((await api<ListResponse<UserSession>>("/auth/sessions?page=1&pageSize=100")).data); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function revoke(item: UserSession) { try { await api(`/auth/sessions/${item.id}/revoke`, { method: "POST" }); notify("تم إلغاء الجلسة."); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر إلغاء الجلسة.", "error"); } }
  return loading ? <Spinner label="جارٍ تحميل الجلسات"/> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>الجلسة</th><th>آخر نشاط</th><th>تنتهي في</th><th>الحالة</th><th></th></tr></thead><tbody>{sessions.map((item) => <tr key={item.id}><td>#{item.id}{item.current && <small>الجلسة الحالية</small>}</td><td>{new Date(item.lastActivityAt).toLocaleString("ar-SA")}</td><td>{new Date(item.expiresAt).toLocaleString("ar-SA")}</td><td><span className={`status-chip ${item.revoked ? "inactive" : "active"}`}>{item.revoked ? "ملغاة" : "نشطة"}</span></td><td>{!item.current && !item.revoked && <Button variant="ghost" icon="ban" onClick={() => void revoke(item)}>إلغاء</Button>}</td></tr>)}</tbody></table></div>;
}
