import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";
import type { CompanyDetails } from "./types";
import { Button, Spinner } from "./ui";

type Notice = (message: string, tone?: "success" | "error") => void;
export function CompanySettingsPage({ notify }: { notify: Notice }) {
  const [company, setCompany] = useState<CompanyDetails | null>(null), [name, setName] = useState(""), [timezone, setTimezone] = useState(""), [makerChecker, setMakerChecker] = useState(true), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState("");
  useEffect(() => { void Promise.all([api<CompanyDetails>("/companies/current"), api<{ data: Array<{ key: string; value: boolean }> }>("/settings")]).then(([details, settings]) => { setCompany(details); setName(details.name); setTimezone(details.timezone); setMakerChecker(settings.data[0]?.value ?? true); }).catch((cause) => setError(cause instanceof Error ? cause.message : "تعذر تحميل الإعدادات.")).finally(() => setLoading(false)); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { const updated = await api<CompanyDetails>("/companies/current", { method: "PATCH", body: JSON.stringify({ name: name.trim(), timezone: timezone.trim() }) }); await api("/settings", { method: "PUT", body: JSON.stringify({ settings: [{ key: "accounting.manual_journal_maker_checker_enabled", value: makerChecker }] }) }); setCompany(updated); notify("تم حفظ إعدادات الشركة وتسجيل التغيير."); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ الإعدادات."); } finally { setSaving(false); } }
  if (loading) return <Spinner label="جارٍ تحميل إعدادات الشركة"/>;
  return <section className="workspace-page"><header className="page-heading"><div><span className="section-kicker">إعدادات مساحة العمل</span><h1>إعدادات الشركة</h1><p>البيانات الأساسية والضوابط المحاسبية المطبقة على الشركة الحالية فقط.</p></div></header>{error && <div className="form-error">{error}</div>}<form className="settings-card" onSubmit={submit}><div className="form-grid"><label><span>اسم الشركة</span><input value={name} onChange={(e) => setName(e.target.value)} required/></label><label><span>المنطقة الزمنية (IANA)</span><input dir="ltr" value={timezone} onChange={(e) => setTimezone(e.target.value)} placeholder="Asia/Riyadh" required/></label><label><span>العملة الأساسية</span><input value={`${company?.baseCurrency.code} — ${company?.baseCurrency.nameAr}`} disabled/></label><label className="check-field full setting-switch"><input type="checkbox" checked={makerChecker} onChange={(e) => setMakerChecker(e.target.checked)}/><span><strong>فصل منشئ القيد عن مرحّله</strong><small>عند التفعيل لا يستطيع منشئ القيد اليدوي ترحيله بنفسه، حتى لو امتلك صلاحية الترحيل. يوصى بإبقائه مفعّلًا.</small></span></label></div><div className="form-actions"><Button type="submit" disabled={saving}>{saving ? "جارٍ الحفظ…" : "حفظ الإعدادات"}</Button></div></form></section>;
}
