import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { validateTreasuryAccount } from "./domain";
import type { Account, CashBankAccount, ListResponse, PaymentMethod } from "./types";
import { Button, EmptyState, Icon, Modal, Pagination, Spinner } from "./ui";

type Notice = (message: string, tone?: "success" | "error") => void;
type Tab = "accounts" | "methods";

export function TreasuryPage({ notify }: { notify: Notice }) {
  const [tab, setTab] = useState<Tab>("accounts"); const [items, setItems] = useState<CashBankAccount[]>([]); const [methods, setMethods] = useState<PaymentMethod[]>([]); const [ledgerAccounts, setLedgerAccounts] = useState<Account[]>([]);
  const [meta, setMeta] = useState({ page: 1, pageSize: 10, total: 0, totalPages: 0 }); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [submittedSearch, setSubmittedSearch] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [cashForm, setCashForm] = useState<CashBankAccount | "new" | null>(null); const [methodForm, setMethodForm] = useState<PaymentMethod | "new" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ page: String(page), pageSize: "10", ...(submittedSearch ? { search: submittedSearch } : {}), ...(type ? { type } : {}), ...(status ? { active: status } : {}) }); const [cash, paymentMethods, accounts] = await Promise.all([api<ListResponse<CashBankAccount>>(`/cash-bank-accounts?${query}`), api<{ data: PaymentMethod[] }>("/payment-methods?includeInactive=true"), api<ListResponse<Account>>("/accounts?page=1&pageSize=100&active=true")]); setItems(cash.data); setMeta(cash.meta); setMethods(paymentMethods.data); setLedgerAccounts(accounts.data.filter((item) => item.isActive && item.allowsPosting)); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل بيانات الخزينة."); } finally { setLoading(false); } }, [page, submittedSearch, type, status]);
  useEffect(() => { void load(); }, [load]);
  const visibleCash = useMemo(() => items.filter((item) => !status || String(item.isActive) === status), [items, status]); const visibleMethods = useMemo(() => methods.filter((item) => !status || String(item.isActive) === status), [methods, status]);
  async function deactivate(kind: Tab, item: CashBankAccount | PaymentMethod) { const reason = window.prompt(`سبب تعطيل «${item.nameAr}» (3 أحرف على الأقل):`); if (!reason || reason.trim().length < 3) return; try { await api(`/${kind === "accounts" ? "cash-bank-accounts" : "payment-methods"}/${item.id}/deactivate`, { method: "POST", body: JSON.stringify({ reason: reason.trim() }) }); notify("تم التعطيل بنجاح."); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : "تعذر التعطيل.", "error"); } }
  return <section className="workspace-page"><header className="page-heading"><div><span className="section-kicker">الخزينة والبنوك</span><h1>إدارة الخزينة</h1><p>تعريف الصناديق والحسابات البنكية وربطها بدليل الأستاذ وإدارة طرق الدفع المتاحة.</p></div><Button icon="plus" onClick={() => tab === "accounts" ? setCashForm("new") : setMethodForm("new")}>{tab === "accounts" ? "حساب خزينة جديد" : "طريقة دفع جديدة"}</Button></header>
    <div className="section-tabs"><button className={tab === "accounts" ? "active" : ""} onClick={() => setTab("accounts")}>الصناديق والحسابات البنكية</button><button className={tab === "methods" ? "active" : ""} onClick={() => setTab("methods")}>طرق الدفع</button></div>
    <div className="toolbar treasury-filters">{tab === "accounts" && <form className="search-box" onSubmit={(e) => { e.preventDefault(); setPage(1); setSubmittedSearch(search.trim()); }}><Icon name="search" size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="الرمز أو الاسم أو البنك" /><button>بحث</button></form>}{tab === "accounts" && <select value={type} onChange={(e) => { setPage(1); setType(e.target.value); }}><option value="">الصناديق والبنوك</option><option value="CASH">صندوق نقدي</option><option value="BANK">حساب بنكي</option></select>}<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">كل الحالات</option><option value="true">نشط</option><option value="false">معطل</option></select></div>
    {error ? <div className="error-panel"><p>{error}</p><Button variant="secondary" onClick={() => void load()}>إعادة المحاولة</Button></div> : loading ? <Spinner label="جارٍ تحميل الخزينة" /> : tab === "accounts" ? <CashTable items={visibleCash} ledgerAccounts={ledgerAccounts} onEdit={setCashForm} onDeactivate={(item) => void deactivate("accounts", item)} onCreate={() => setCashForm("new")} /> : <MethodsTable items={visibleMethods} onEdit={setMethodForm} onDeactivate={(item) => void deactivate("methods", item)} onCreate={() => setMethodForm("new")} />}
    {tab === "accounts" && <Pagination {...meta} page={page} onChange={setPage} />}
    {cashForm && <CashForm account={cashForm === "new" ? null : cashForm} ledgerAccounts={ledgerAccounts} onClose={() => setCashForm(null)} onSaved={async () => { setCashForm(null); notify(cashForm === "new" ? "تم إنشاء حساب الخزينة." : "تم تحديث حساب الخزينة."); await load(); }} />}
    {methodForm && <MethodForm method={methodForm === "new" ? null : methodForm} onClose={() => setMethodForm(null)} onSaved={async () => { setMethodForm(null); notify(methodForm === "new" ? "تم إنشاء طريقة الدفع." : "تم تحديث طريقة الدفع."); await load(); }} />}
  </section>;
}

function CashTable({ items, ledgerAccounts, onEdit, onDeactivate, onCreate }: { items: CashBankAccount[]; ledgerAccounts: Account[]; onEdit: (item: CashBankAccount) => void; onDeactivate: (item: CashBankAccount) => void; onCreate: () => void }) {
  if (!items.length) return <EmptyState title="لا توجد حسابات خزينة" description="اربط صندوقًا أو حسابًا بنكيًا بحساب أستاذ قابل للترحيل." action={<Button icon="plus" onClick={onCreate}>إنشاء حساب خزينة</Button>} />;
  return <div className="data-table-wrap"><table className="data-table"><thead><tr><th>الحساب</th><th>النوع</th><th>حساب الأستاذ</th><th>البنك</th><th>البيانات المقنّعة</th><th>الحالة</th><th></th></tr></thead><tbody>{items.map((item) => { const ledger = ledgerAccounts.find((account) => account.id === item.ledgerAccountId); return <tr key={item.id}><td><strong dir="ltr">{item.code}</strong><small>{item.nameAr}</small></td><td>{item.accountType === "BANK" ? "حساب بنكي" : "صندوق نقدي"}</td><td>{ledger ? `${ledger.code} — ${ledger.nameAr}` : item.ledgerAccountId}</td><td>{item.bankName || "—"}</td><td><span dir="ltr">{item.ibanMasked || item.accountNumberMasked || "—"}</span></td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? "نشط" : "معطل"}</span></td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>تعديل</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>تعطيل</Button>}</div></td></tr>; })}</tbody></table></div>;
}

function MethodsTable({ items, onEdit, onDeactivate, onCreate }: { items: PaymentMethod[]; onEdit: (item: PaymentMethod) => void; onDeactivate: (item: PaymentMethod) => void; onCreate: () => void }) {
  if (!items.length) return <EmptyState title="لا توجد طرق دفع" description="أضف طريقة دفع خاصة بالشركة." action={<Button icon="plus" onClick={onCreate}>إضافة طريقة</Button>} />;
  return <div className="data-table-wrap"><table className="data-table"><thead><tr><th>الرمز</th><th>الاسم</th><th>الرقم المرجعي</th><th>النطاق</th><th>الحالة</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td dir="ltr"><strong>{item.code}</strong></td><td>{item.nameAr}</td><td>{item.requiresReference ? "إلزامي" : "اختياري"}</td><td>{item.scope === "GLOBAL" ? <span className="reference-badge">مرجعية عامة</span> : "خاصة بالشركة"}</td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? "نشطة" : "معطلة"}</span></td><td>{item.scope === "COMPANY" && <div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>تعديل</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>تعطيل</Button>}</div>}</td></tr>)}</tbody></table></div>;
}

function CashForm({ account, ledgerAccounts, onClose, onSaved }: { account: CashBankAccount | null; ledgerAccounts: Account[]; onClose: () => void; onSaved: () => void }) {
  const [ledgerAccountId, setLedger] = useState(account?.ledgerAccountId ?? ""); const [accountType, setType] = useState<"CASH" | "BANK">(account?.accountType ?? "CASH"); const [code, setCode] = useState(account?.code ?? ""); const [nameAr, setNameAr] = useState(account?.nameAr ?? ""); const [nameEn, setNameEn] = useState(account?.nameEn ?? ""); const [bankName, setBankName] = useState(account?.bankName ?? ""); const [accountNumber, setAccountNumber] = useState(""); const [iban, setIban] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); const errors = validateTreasuryAccount({ accountType, ledgerAccountId, bankName }); if (errors.length) { setError(errors.join(" ")); return; } setSaving(true); setError(""); try { await api(account ? `/cash-bank-accounts/${account.id}` : "/cash-bank-accounts", { method: account ? "PATCH" : "POST", body: JSON.stringify({ ledgerAccountId, accountType, code: code.trim(), nameAr: nameAr.trim(), nameEn: nameEn.trim() || null, bankName: accountType === "BANK" ? bankName.trim() : null, ...((accountNumber || !account) ? { accountNumber: accountNumber || null } : {}), ...((iban || !account) ? { iban: iban || null } : {}) }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ حساب الخزينة."); } finally { setSaving(false); } }
  return <Modal title={account ? "تعديل حساب الخزينة" : "حساب خزينة جديد"} description="تُحفظ آخر أربعة أرقام فقط من رقم الحساب وIBAN، ولا يمكن استرجاع النص الكامل لاحقًا." onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label><span>النوع</span><select value={accountType} onChange={(e) => { const value = e.target.value as "CASH" | "BANK"; setType(value); if (value === "CASH") setBankName(""); }}><option value="CASH">صندوق نقدي</option><option value="BANK">حساب بنكي</option></select></label><label><span>الرمز</span><input value={code} onChange={(e) => setCode(e.target.value)} required /></label><label><span>الاسم العربي</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label><span>الاسم الإنجليزي</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label><label className="full"><span>حساب الأستاذ القابل للترحيل</span><select value={ledgerAccountId} onChange={(e) => setLedger(e.target.value)} required><option value="">اختر الحساب</option>{ledgerAccounts.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.nameAr}</option>)}</select></label>{accountType === "BANK" && <><label><span>اسم البنك</span><input value={bankName} onChange={(e) => setBankName(e.target.value)} required /></label><label><span>رقم الحساب {account?.accountNumberMasked && `(الحالي ${account.accountNumberMasked})`}</span><input dir="ltr" value={accountNumber} onChange={(e) => setAccountNumber(e.target.value)} placeholder={account ? "اتركه فارغًا دون تغيير" : ""} /></label><label className="full"><span>IBAN {account?.ibanMasked && `(الحالي ${account.ibanMasked})`}</span><input dir="ltr" value={iban} onChange={(e) => setIban(e.target.value)} placeholder={account ? "اتركه فارغًا دون تغيير" : "SA…"} /></label></>}</div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button type="submit" disabled={saving}>{saving ? "جارٍ الحفظ…" : "حفظ"}</Button></div></form></Modal>;
}

function MethodForm({ method, onClose, onSaved }: { method: PaymentMethod | null; onClose: () => void; onSaved: () => void }) {
  const [code, setCode] = useState(method?.code ?? ""); const [nameAr, setNameAr] = useState(method?.nameAr ?? ""); const [requiresReference, setRequired] = useState(method?.requiresReference ?? false); const [error, setError] = useState("");
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); try { await api(method ? `/payment-methods/${method.id}` : "/payment-methods", { method: method ? "PATCH" : "POST", body: JSON.stringify({ code: code.trim().toUpperCase(), nameAr: nameAr.trim(), requiresReference }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ طريقة الدفع."); } }
  return <Modal title={method ? "تعديل طريقة الدفع" : "طريقة دفع جديدة"} description="طرق الدفع التي تضيفها هنا تخص الشركة الحالية فقط؛ الطرق العامة تبقى للعرض دون تعديل." onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label><span>الرمز</span><input dir="ltr" value={code} onChange={(e) => setCode(e.target.value)} required /></label><label><span>الاسم العربي</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label className="check-field full"><input type="checkbox" checked={requiresReference} onChange={(e) => setRequired(e.target.checked)} /><span>يتطلب رقمًا مرجعيًا عند استخدامه</span></label></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>إلغاء</Button><Button type="submit">حفظ</Button></div></form></Modal>;
}
