import {
  localizedReferenceName,
  translate as t } from "./i18n";
import { FormEvent,
  useCallback,
  useEffect,
  useMemo,
  useState } from "react";
import { api } from "./api";
import { validateTreasuryAccount } from "./domain";
import type { Account,
  CashBankAccount,
  ListResponse,
  PaymentMethod } from "./types";
import { Button,
  EmptyState,
  Icon,
  Modal,
  Pagination,
  Spinner,
  PageHeader,
} from "./ui";

type Notice = (message: string, tone?: "success" | "error") => void;
type Tab = "accounts" | "methods";

export function TreasuryPage({ notify }: { notify: Notice }) {
  const [tab, setTab] = useState<Tab>("accounts"); const [items, setItems] = useState<CashBankAccount[]>([]); const [methods, setMethods] = useState<PaymentMethod[]>([]); const [ledgerAccounts, setLedgerAccounts] = useState<Account[]>([]);
  const [meta, setMeta] = useState({ page: 1, pageSize: 10, total: 0, totalPages: 0 }); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [submittedSearch, setSubmittedSearch] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [cashForm, setCashForm] = useState<CashBankAccount | "new" | null>(null); const [methodForm, setMethodForm] = useState<PaymentMethod | "new" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ page: String(page), pageSize: "10", ...(submittedSearch ? { search: submittedSearch } : {}), ...(type ? { type } : {}), ...(status ? { active: status } : {}) }); const [cash, paymentMethods, accounts] = await Promise.all([api<ListResponse<CashBankAccount>>(`/cash-bank-accounts?${query}`), api<{ data: PaymentMethod[] }>("/payment-methods?includeInactive=true"), api<ListResponse<Account>>("/accounts?page=1&pageSize=100&active=true")]); setItems(cash.data); setMeta(cash.meta); setMethods(paymentMethods.data); setLedgerAccounts(accounts.data.filter((item) => item.isActive && item.allowsPosting)); } catch (cause) { setError(cause instanceof Error ? cause.message : t("pages.treasury.001")); } finally { setLoading(false); } }, [page, submittedSearch, type, status]);
  useEffect(() => { void load(); }, [load]);
  const visibleCash = useMemo(() => items.filter((item) => !status || String(item.isActive) === status), [items, status]); const visibleMethods = useMemo(() => methods.filter((item) => !status || String(item.isActive) === status), [methods, status]);
  async function deactivate(kind: Tab, item: CashBankAccount | PaymentMethod) { const reason = window.prompt(t("pages.accounts.002", { value1: localizedReferenceName(item) })); if (!reason || reason.trim().length < 3) return; try { await api(`/${kind === "accounts" ? "cash-bank-accounts" : "payment-methods"}/${item.id}/deactivate`, { method: "POST", body: JSON.stringify({ version: item.version, reason: reason.trim() }) }); notify(t("pages.treasury.003")); await load(); } catch (cause) { notify(cause instanceof Error ? cause.message : t("pages.accounts.005"), "error"); } }
  return <section className="workspace-page"><PageHeader kicker={t("pages.treasury.005")} title={t("pages.treasury.006")} description={t("pages.treasury.007")} actions={<Button icon="plus" onClick={() => tab === "accounts" ? setCashForm("new") : setMethodForm("new")}>{tab === "accounts" ? t("pages.treasury.008") : t("pages.treasury.009")}</Button>} />
    <div className="section-tabs"><button className={tab === "accounts" ? "active" : ""} onClick={() => setTab("accounts")}>{t("pages.treasury.010")}</button><button className={tab === "methods" ? "active" : ""} onClick={() => setTab("methods")}>{t("pages.treasury.011")}</button></div>
    <div className="toolbar treasury-filters">{tab === "accounts" && <form className="search-box" onSubmit={(e) => { e.preventDefault(); setPage(1); setSubmittedSearch(search.trim()); }}><Icon name="search" size={18} /><input aria-label={t("pages.treasury.012")} value={search} onChange={(e) => setSearch(e.target.value)} placeholder={t("pages.treasury.012")} /><button type="submit">{t("pages.accounts.026")}</button></form>}{tab === "accounts" && <select aria-label={t("pages.treasury.014")} value={type} onChange={(e) => { setPage(1); setType(e.target.value); }}><option value="">{t("pages.treasury.014")}</option><option value="CASH">{t("pages.treasury.015")}</option><option value="BANK">{t("pages.treasury.016")}</option></select>}<select aria-label={t("pages.accounts.027")} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">{t("pages.accounts.027")}</option><option value="true">{t("pages.accounts.028")}</option><option value="false">{t("pages.accounts.029")}</option></select></div>
    {error ? <div className="error-panel" role="alert"><p>{error}</p><Button variant="secondary" onClick={() => void load()}>{t("pages.accounts.030")}</Button></div> : loading ? <Spinner label={t("pages.treasury.021")} /> : tab === "accounts" ? <CashTable items={visibleCash} ledgerAccounts={ledgerAccounts} onEdit={setCashForm} onDeactivate={(item) => void deactivate("accounts", item)} onCreate={() => setCashForm("new")} /> : <MethodsTable items={visibleMethods} onEdit={setMethodForm} onDeactivate={(item) => void deactivate("methods", item)} onCreate={() => setMethodForm("new")} />}
    {tab === "accounts" && <Pagination {...meta} page={page} onChange={setPage} />}
    {cashForm && <CashForm account={cashForm === "new" ? null : cashForm} ledgerAccounts={ledgerAccounts} onClose={() => setCashForm(null)} onSaved={async () => { setCashForm(null); notify(cashForm === "new" ? t("pages.treasury.022") : t("pages.treasury.023")); await load(); }} />}
    {methodForm && <MethodForm method={methodForm === "new" ? null : methodForm} onClose={() => setMethodForm(null)} onSaved={async () => { setMethodForm(null); notify(methodForm === "new" ? t("pages.treasury.024") : t("pages.treasury.025")); await load(); }} />}
  </section>;
}
function CashTable({ items, ledgerAccounts, onEdit, onDeactivate, onCreate }: { items: CashBankAccount[]; ledgerAccounts: Account[]; onEdit: (item: CashBankAccount) => void; onDeactivate: (item: CashBankAccount) => void; onCreate: () => void }) {
  if (!items.length) return <EmptyState title={t("pages.treasury.026")} description={t("pages.treasury.027")} action={<Button icon="plus" onClick={onCreate}>{t("pages.treasury.028")}</Button>} />;
  return <div className="data-table-wrap" role="region" tabIndex={0} aria-label={t("common.scrollableTable")}><table className="data-table"><thead><tr><th>{t("pages.accounts.039")}</th><th>{t("pages.accounts.040")}</th><th>{t("pages.treasury.031")}</th><th>{t("pages.treasury.032")}</th><th>{t("pages.treasury.033")}</th><th>{t("pages.accounts.043")}</th><th></th></tr></thead><tbody>{items.map((item) => { const ledger = ledgerAccounts.find((account) => account.id === item.ledgerAccountId); return <tr key={item.id}><td><strong dir="ltr">{item.code}</strong><small>{localizedReferenceName(item)}</small></td><td>{item.accountType === "BANK" ? t("pages.treasury.016") : t("pages.treasury.015")}</td><td>{ledger ? `${ledger.code} — ${localizedReferenceName(ledger)}` : item.ledgerAccountId}</td><td>{item.bankName || "—"}</td><td><span dir="ltr">{item.ibanMasked || item.accountNumberMasked || "—"}</span></td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? t("pages.accounts.028") : t("pages.accounts.029")}</span></td><td><div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>{t("pages.accounts.048")}</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>{t("pages.accounts.049")}</Button>}</div></td></tr>; })}</tbody></table></div>;
}
function MethodsTable({ items, onEdit, onDeactivate, onCreate }: { items: PaymentMethod[]; onEdit: (item: PaymentMethod) => void; onDeactivate: (item: PaymentMethod) => void; onCreate: () => void }) {
  if (!items.length) return <EmptyState title={t("pages.treasury.037")} description={t("pages.treasury.038")} action={<Button icon="plus" onClick={onCreate}>{t("pages.treasury.039")}</Button>} />;
  return <div className="data-table-wrap" role="region" tabIndex={0} aria-label={t("common.scrollableTable")}><table className="data-table"><thead><tr><th>{t("pages.accounts.059")}</th><th>{t("pages.fiscal.054")}</th><th>{t("pages.treasury.042")}</th><th>{t("pages.treasury.043")}</th><th>{t("pages.accounts.043")}</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td dir="ltr"><strong>{item.code}</strong></td><td>{localizedReferenceName(item)}</td><td>{item.requiresReference ? t("pages.treasury.044") : t("pages.treasury.045")}</td><td>{item.scope === "GLOBAL" ? <span className="reference-badge">{t("pages.treasury.046")}</span> : t("pages.treasury.047")}</td><td><span className={`status-chip ${item.isActive ? "active" : "inactive"}`}>{item.isActive ? t("pages.admin.065") : t("pages.purchase-invoices.135")}</span></td><td>{item.scope === "COMPANY" && <div className="inline-actions"><Button variant="ghost" icon="edit" onClick={() => onEdit(item)}>{t("pages.accounts.048")}</Button>{item.isActive && <Button variant="ghost" icon="ban" onClick={() => onDeactivate(item)}>{t("pages.accounts.049")}</Button>}</div>}</td></tr>)}</tbody></table></div>;
}
function CashForm({ account, ledgerAccounts, onClose, onSaved }: { account: CashBankAccount | null; ledgerAccounts: Account[]; onClose: () => void; onSaved: () => void }) {
  const [ledgerAccountId, setLedger] = useState(account?.ledgerAccountId ?? ""); const [accountType, setType] = useState<"CASH" | "BANK">(account?.accountType ?? "CASH"); const [nameAr, setNameAr] = useState(account?.nameAr ?? ""); const [nameEn, setNameEn] = useState(account?.nameEn ?? ""); const [bankName, setBankName] = useState(account?.bankName ?? ""); const [accountNumber, setAccountNumber] = useState(""); const [iban, setIban] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); const errors = validateTreasuryAccount({ accountType, ledgerAccountId, bankName }); if (errors.length) { setError(errors.join(" ")); return; } setSaving(true); setError(""); try { await api(account ? `/cash-bank-accounts/${account.id}` : "/cash-bank-accounts", { method: account ? "PATCH" : "POST", body: JSON.stringify({ ...(account ? { version: account.version } : {}), ledgerAccountId, accountType, nameAr: nameAr.trim(), nameEn: nameEn.trim() || null, bankName: accountType === "BANK" ? bankName.trim() : null, ...((accountNumber || !account) ? { accountNumber: accountNumber || null } : {}), ...((iban || !account) ? { iban: iban || null } : {}) }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("pages.treasury.050")); } finally { setSaving(false); } }
  return <Modal title={account ? t("pages.treasury.051") : t("pages.treasury.008")} description={t("pages.treasury.052")} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}<div className="form-grid"><label><span>{t("pages.accounts.040")}</span><select value={accountType} onChange={(e) => { const value = e.target.value as "CASH" | "BANK"; setType(value); if (value === "CASH") setBankName(""); }}><option value="CASH">{t("pages.treasury.015")}</option><option value="BANK">{t("pages.treasury.016")}</option></select></label>{account ? <label><span>{t("pages.accounts.059")}</span><input dir="ltr" value={account.code} readOnly /></label> : <div className="inline-notice neutral full">{t("common.autoGeneratedCode")}</div>}<label><span>{t("pages.accounts.061")}</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label><span>{t("pages.accounts.055")}</span><input dir="ltr" value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label><label className="full"><span>{t("pages.treasury.055")}</span><select value={ledgerAccountId} onChange={(e) => setLedger(e.target.value)} required><option value="">{t("pages.customers.044")}</option>{ledgerAccounts.map((item) => <option key={item.id} value={item.id}>{item.code} — {localizedReferenceName(item)}</option>)}</select></label>{accountType === "BANK" && <><label><span>{t("pages.treasury.057")}</span><input value={bankName} onChange={(e) => setBankName(e.target.value)} required /></label><label><span>{t("pages.treasury.058")}{account?.accountNumberMasked && t("pages.treasury.059", { value1: account.accountNumberMasked })}</span><input dir="ltr" value={accountNumber} onChange={(e) => setAccountNumber(e.target.value)} placeholder={account ? t("pages.treasury.060") : ""} /></label><label className="full"><span>IBAN {account?.ibanMasked && t("pages.treasury.059", { value1: account.ibanMasked })}</span><input dir="ltr" value={iban} onChange={(e) => setIban(e.target.value)} placeholder={account ? t("pages.treasury.060") : "SA…"} /></label></>}</div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>{t("pages.accounts.065")}</Button><Button type="submit" disabled={saving}>{saving ? t("pages.accounts.066") : t("pages.accounts.067")}</Button></div></form></Modal>;
}

function MethodForm({ method, onClose, onSaved }: { method: PaymentMethod | null; onClose: () => void; onSaved: () => void }) {
  const [nameAr, setNameAr] = useState(method?.nameAr ?? ""); const [requiresReference, setRequired] = useState(method?.requiresReference ?? false); const [error, setError] = useState("");
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); try { await api(method ? `/payment-methods/${method.id}` : "/payment-methods", { method: method ? "PATCH" : "POST", body: JSON.stringify({ ...(method ? { version: method.version } : {}), nameAr: nameAr.trim(), requiresReference }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("pages.treasury.064")); } }
  return <Modal title={method ? t("pages.treasury.065") : t("pages.treasury.009")} description={t("pages.treasury.066")} onClose={onClose}><form className="document-form" onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}<div className="form-grid">{method ? <label><span>{t("pages.accounts.059")}</span><input dir="ltr" value={method.code} readOnly /></label> : <div className="inline-notice neutral full">{t("common.autoGeneratedCode")}</div>}<label><span>{t("pages.accounts.061")}</span><input value={nameAr} onChange={(e) => setNameAr(e.target.value)} required /></label><label className="check-field full"><input type="checkbox" checked={requiresReference} onChange={(e) => setRequired(e.target.checked)} /><span>{t("pages.treasury.067")}</span></label></div><div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>{t("pages.accounts.065")}</Button><Button type="submit">{t("pages.accounts.067")}</Button></div></form></Modal>;
}
