export const inventoryValuationReportCopy = {
  ar: {
    tab: "تقارير المخزون", title: "كشف تقييم المخزون الحالي", description: "لقطة من الأرصدة الحالية وقت التوليد، وليست كشفًا تاريخيًا.", download: "تنزيل Excel", downloaded: "تم تنزيل كشف التقييم.", loadError: "تعذر تحميل كشف التقييم.", loading: "جارٍ تحميل كشف التقييم", empty: "لا توجد أرصدة تطابق الفلاتر.", allWarehouses: "كل المستودعات", allItems: "كل الأصناف", allStatuses: "كل حالات التقييم", valued: "مقيّم", unvalued: "غير مقيّم", total: "إجمالي القيمة المقيّمة", rows: "عدد الأرصدة", warning: "يوجد {count} رصيد غير مقيّم. لم تدخل قيمته في الإجمالي.", item: "الصنف", unit: "الوحدة", warehouse: "المستودع", quantity: "الكمية", averageCost: "متوسط تكلفة الوحدة", value: "القيمة الإجمالية", status: "حالة التقييم", generated: "وقت التوليد", search: "ابحث بالرمز أو الاسم",
  },
  en: {
    tab: "Inventory reports", title: "Current inventory valuation", description: "A snapshot of current balances at generation time; this is not a historical report.", download: "Download Excel", downloaded: "Valuation report downloaded.", loadError: "Could not load the valuation report.", loading: "Loading valuation report", empty: "No balances match the filters.", allWarehouses: "All warehouses", allItems: "All items", allStatuses: "All valuation statuses", valued: "Valued", unvalued: "Unvalued", total: "Total valued inventory", rows: "Balance rows", warning: "{count} balance(s) are unvalued and excluded from the total.", item: "Item", unit: "Unit", warehouse: "Warehouse", quantity: "Quantity", averageCost: "Average unit cost", value: "Total value", status: "Valuation status", generated: "Generated at", search: "Search code or name",
  },
  ur: {
    tab: "انوینٹری رپورٹس", title: "موجودہ انوینٹری ویلیوایشن", description: "یہ بنائے جانے کے وقت موجودہ بیلنس کی تصویر ہے، تاریخی رپورٹ نہیں۔", download: "Excel ڈاؤن لوڈ", downloaded: "رپورٹ ڈاؤن لوڈ ہو گئی۔", loadError: "رپورٹ لوڈ نہیں ہو سکی۔", loading: "رپورٹ لوڈ ہو رہی ہے", empty: "فلٹر سے مماثل بیلنس نہیں۔", allWarehouses: "تمام گودام", allItems: "تمام اشیاء", allStatuses: "تمام حالتیں", valued: "قیمت شدہ", unvalued: "غیر قیمت شدہ", total: "کل قیمت", rows: "بیلنس قطاریں", warning: "{count} بیلنس غیر قیمت شدہ ہیں۔", item: "شے", unit: "اکائی", warehouse: "گودام", quantity: "مقدار", averageCost: "اوسط لاگت", value: "کل قیمت", status: "حالت", generated: "بنایا گیا", search: "کوڈ یا نام تلاش کریں",
  },
  hi: {
    tab: "इन्वेंट्री रिपोर्ट", title: "वर्तमान इन्वेंट्री मूल्यांकन", description: "यह निर्माण समय के वर्तमान शेष का स्नैपशॉट है; ऐतिहासिक रिपोर्ट नहीं।", download: "Excel डाउनलोड", downloaded: "रिपोर्ट डाउनलोड हुई।", loadError: "रिपोर्ट लोड नहीं हुई।", loading: "रिपोर्ट लोड हो रही है", empty: "फ़िल्टर से मेल खाता कोई शेष नहीं।", allWarehouses: "सभी गोदाम", allItems: "सभी आइटम", allStatuses: "सभी स्थिति", valued: "मूल्यांकित", unvalued: "अमूल्यांकित", total: "कुल मूल्य", rows: "शेष पंक्तियाँ", warning: "{count} शेष अमूल्यांकित हैं।", item: "आइटम", unit: "इकाई", warehouse: "गोदाम", quantity: "मात्रा", averageCost: "औसत इकाई लागत", value: "कुल मूल्य", status: "मूल्यांकन स्थिति", generated: "निर्मित", search: "कोड या नाम खोजें",
  },
} as const;
