-- SC-1A only: independent service definitions. No module activation or entitlement grant.
CREATE TABLE `service_categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `name_ar` VARCHAR(160) NOT NULL,
  `name_en` VARCHAR(160) NULL,
  `description` VARCHAR(1000) NULL,
  `status` ENUM('ACTIVE','INACTIVE','RETIRED') NOT NULL DEFAULT 'ACTIVE',
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `service_categories_public_id_key` (`public_id`),
  UNIQUE KEY `service_categories_id_company_id_key` (`id`,`company_id`),
  KEY `service_categories_company_id_status_name_ar_id_idx` (`company_id`,`status`,`name_ar`,`id`),
  CONSTRAINT `service_categories_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_categories_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_categories_updated_by_id_fkey` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `service_offerings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `code` VARCHAR(40) NOT NULL,
  `name_ar` VARCHAR(200) NOT NULL,
  `name_en` VARCHAR(200) NULL,
  `description` VARCHAR(1000) NULL,
  `status` ENUM('DRAFT','ACTIVE','INACTIVE','RETIRED') NOT NULL DEFAULT 'DRAFT',
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `service_offerings_public_id_key` (`public_id`),
  UNIQUE KEY `service_offerings_company_id_code_key` (`company_id`,`code`),
  UNIQUE KEY `service_offerings_id_company_id_key` (`id`,`company_id`),
  KEY `service_offerings_company_id_status_created_at_id_idx` (`company_id`,`status`,`created_at`,`id`),
  KEY `service_offerings_category_id_company_id_status_idx` (`category_id`,`company_id`,`status`),
  CONSTRAINT `service_offerings_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_offerings_category_id_company_id_fkey` FOREIGN KEY (`category_id`,`company_id`) REFERENCES `service_categories` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_offerings_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_offerings_updated_by_id_fkey` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `service_offering_variants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `offering_id` BIGINT UNSIGNED NOT NULL,
  `name_ar` VARCHAR(160) NOT NULL,
  `name_en` VARCHAR(160) NULL,
  `pricing_unit` ENUM('EACH','HOUR','DAY','SESSION','MONTH') NOT NULL,
  `available_from` DATE NULL,
  `available_until` DATE NULL,
  `default_revenue_account_id` BIGINT UNSIGNED NULL,
  `default_output_tax_rate_id` BIGINT UNSIGNED NULL,
  `status` ENUM('DRAFT','ACTIVE','INACTIVE','RETIRED') NOT NULL DEFAULT 'DRAFT',
  `first_activated_at` DATETIME(3) NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `service_offering_variants_public_id_key` (`public_id`),
  UNIQUE KEY `service_offering_variants_id_company_id_key` (`id`,`company_id`),
  KEY `svc_variant_offering_order_idx` (`offering_id`,`company_id`,`created_at`,`id`),
  KEY `svc_variant_availability_idx` (`company_id`,`status`,`available_from`,`available_until`),
  KEY `svc_variant_revenue_account_idx` (`default_revenue_account_id`,`company_id`),
  KEY `svc_variant_output_tax_idx` (`default_output_tax_rate_id`,`company_id`),
  CONSTRAINT `service_offering_variants_availability_chk` CHECK (`available_from` IS NULL OR `available_until` IS NULL OR `available_from` < `available_until`),
  CONSTRAINT `service_offering_variants_activation_chk` CHECK (`status` NOT IN ('ACTIVE','INACTIVE') OR `first_activated_at` IS NOT NULL),
  CONSTRAINT `service_offering_variants_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_offering_variants_offering_id_company_id_fkey` FOREIGN KEY (`offering_id`,`company_id`) REFERENCES `service_offerings` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `svc_variant_revenue_account_fk` FOREIGN KEY (`default_revenue_account_id`,`company_id`) REFERENCES `accounts` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `svc_variant_output_tax_fk` FOREIGN KEY (`default_output_tax_rate_id`,`company_id`) REFERENCES `tax_rates` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_offering_variants_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `service_offering_variants_updated_by_id_fkey` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
