-- GPM-3 stores only Finish-to-Start links inside one independent project and company.
CREATE TABLE `general_project_task_dependencies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `predecessor_task_id` BIGINT UNSIGNED NOT NULL,
  `successor_task_id` BIGINT UNSIGNED NOT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  `removed_at` DATETIME(3) NULL,
  `removal_reason` VARCHAR(500) NULL,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `gp_dependencies_public_id_key` (`public_id`),
  UNIQUE KEY `gp_dependencies_project_pair_key` (`project_id`, `predecessor_task_id`, `successor_task_id`),
  KEY `gp_dependencies_company_project_active_idx` (`company_id`, `project_id`, `is_active`),
  KEY `gp_dependencies_predecessor_scope_idx` (`predecessor_task_id`, `project_id`, `company_id`),
  KEY `gp_dependencies_successor_scope_idx` (`successor_task_id`, `project_id`, `company_id`, `is_active`),
  CONSTRAINT `gp_dependencies_not_self_chk` CHECK (`predecessor_task_id` <> `successor_task_id`),
  CONSTRAINT `gp_dependencies_company_fk` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `gp_dependencies_project_fk` FOREIGN KEY (`project_id`, `company_id`) REFERENCES `general_projects` (`id`, `company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `gp_dependencies_predecessor_fk` FOREIGN KEY (`predecessor_task_id`, `project_id`, `company_id`) REFERENCES `general_project_tasks` (`id`, `project_id`, `company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `gp_dependencies_successor_fk` FOREIGN KEY (`successor_task_id`, `project_id`, `company_id`) REFERENCES `general_project_tasks` (`id`, `project_id`, `company_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `gp_dependencies_created_by_fk` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `gp_dependencies_updated_by_fk` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
