-- Durable, resumable self-registration. No tenant or user is created before
-- email ownership is verified; provisioning and completion are committed atomically.
CREATE TABLE `registration_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(80) NOT NULL,
  `email_normalized` VARCHAR(320) NOT NULL,
  `password_hash` VARCHAR(255) NULL,
  `display_name` VARCHAR(160) NOT NULL,
  `organization_name` VARCHAR(200) NOT NULL,
  `company_name` VARCHAR(200) NOT NULL,
  `timezone` VARCHAR(64) NOT NULL,
  `base_currency_code` CHAR(3) NOT NULL,
  `locale` VARCHAR(10) NOT NULL DEFAULT 'ar',
  `chart_template_code` VARCHAR(80) NOT NULL DEFAULT 'SMALL_BUSINESS_GENERAL',
  `verification_token_hash` BINARY(32) NOT NULL,
  `verification_expires_at` DATETIME(3) NOT NULL,
  `status` ENUM('PENDING_EMAIL', 'EMAIL_VERIFIED', 'PROVISIONING', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING_EMAIL',
  `delivery_status` ENUM('PENDING', 'SENT', 'FAILED') NOT NULL DEFAULT 'PENDING',
  `delivery_attempts` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `verified_at` DATETIME(3) NULL,
  `provisioning_started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `provisioned_organization_id` BIGINT UNSIGNED NULL,
  `provisioned_company_id` BIGINT UNSIGNED NULL,
  `provisioned_user_id` BIGINT UNSIGNED NULL,
  `last_error_code` VARCHAR(80) NULL,
  `initial_ip_address` VARCHAR(64) NULL,
  `initial_user_agent` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `registration_requests_public_id_key` (`public_id`),
  UNIQUE INDEX `registration_requests_email_normalized_key` (`email_normalized`),
  UNIQUE INDEX `registration_requests_verification_token_hash_key` (`verification_token_hash`),
  INDEX `registration_requests_status_verification_expires_at_idx` (`status`, `verification_expires_at`),
  INDEX `registration_requests_provisioned_company_id_idx` (`provisioned_company_id`),
  INDEX `registration_requests_provisioned_user_id_idx` (`provisioned_user_id`),
  CONSTRAINT `registration_requests_provisioned_organization_id_fkey` FOREIGN KEY (`provisioned_organization_id`) REFERENCES `organizations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `registration_requests_provisioned_company_id_fkey` FOREIGN KEY (`provisioned_company_id`) REFERENCES `companies`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `registration_requests_provisioned_user_id_fkey` FOREIGN KEY (`provisioned_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `registration_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `registration_request_id` BIGINT UNSIGNED NULL,
  `email_hash` BINARY(32) NOT NULL,
  `event_type` VARCHAR(80) NOT NULL,
  `severity` ENUM('INFO', 'WARNING', 'HIGH', 'CRITICAL') NOT NULL,
  `ip_address` VARCHAR(64) NULL,
  `user_agent` VARCHAR(500) NULL,
  `details` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `registration_events_registration_request_id_created_at_idx` (`registration_request_id`, `created_at`),
  INDEX `registration_events_email_hash_created_at_idx` (`email_hash`, `created_at`),
  INDEX `registration_events_severity_created_at_idx` (`severity`, `created_at`),
  CONSTRAINT `registration_events_registration_request_id_fkey` FOREIGN KEY (`registration_request_id`) REFERENCES `registration_requests`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
